import { test, expect } from '@playwright/test';

test.describe('Smoke Tests', () => {
  test('App loads successfully', async ({ page }) => {
    // GIVEN - Navigate to the app
    await page.goto('/');

    // THEN - App should load and show main content
    await expect(page).toHaveTitle(/Hallenfußball/i);

    // Page should be interactive (no loading spinner stuck)
    await expect(page.locator('body')).toBeVisible();
  });

  test('Viewport meta is correct for mobile', async ({ page }) => {
    // GIVEN - Navigate to the app
    await page.goto('/');

    // THEN - Viewport meta should be set correctly
    const viewport = await page.locator('meta[name="viewport"]').getAttribute('content');

    // Required attributes
    expect(viewport).toContain('width=device-width');
    expect(viewport).toContain('initial-scale=1');

    // Safe area support (for notch devices)
    expect(viewport).toContain('viewport-fit=cover');

    // Accessibility: must NOT disable user scaling
    expect(viewport).not.toContain('user-scalable=no');
    expect(viewport).not.toContain('maximum-scale=1');
  });

  test('PWA meta tags are present', async ({ page }) => {
    // GIVEN - Navigate to the app
    await page.goto('/');

    // THEN - PWA meta tags should be present
    const themeColor = await page.locator('meta[name="theme-color"]').getAttribute('content');
    expect(themeColor).toBeTruthy();

    // Apple mobile web app meta tags
    const appleCapable = await page.locator('meta[name="apple-mobile-web-app-capable"]').getAttribute('content');
    expect(appleCapable).toBe('yes');

    const appleStatusBar = await page.locator('meta[name="apple-mobile-web-app-status-bar-style"]').getAttribute('content');
    expect(appleStatusBar).toBeTruthy();

    // Note: manifest link is generated by vite-plugin-pwa at build time
    // In dev mode it may not be present, so we don't test for it here
  });
});
